WITH REZ_CTE AS (
	SELECT
		C.CONTRACT_ID,
		ACS.BASE_AMOUNT AS REZ_AMOUNT
	FROM SR_BANK.ACCOUNT_SNAPSHOT ACS
	JOIN SR_BANK.ACCOUNT A 
		ON A.ID = ACS.ACCOUNT_ID
	JOIN SR_BANK.CONTRACT_ACCOUNT C 
		ON C.ACCOUNT_ID = A.ID
	WHERE ACS.SNAPSHOT_DATE = TO_DATE(:date_param, 'DD.MM.YYYY')
		AND ACS.BASE_AMOUNT <> 0
		AND SUBSTR(A.ACCOUNT_NUMBER, 1, 4) IN ('3690', '3692')
)
SELECT
	SUBSTR(A.ACCOUNT_NUMBER, 1, 4) AS R020,
	TO_DATE(:date_param, 'DD.MM.YYYY') AS RDATE,
	A.ACCOUNT_NUMBER,
	CA.CONTRACT_ID,
	ACS.BASE_AMOUNT,
	NVL(RC.REZ_AMOUNT, 0) AS RESERVE,
	CCF.CODE,
	CCF.VALUE AS CCF,
	CASE
		WHEN CCF.CODE IS NULL AND SUBSTR(A.ACCOUNT_NUMBER, 1, 4) IN ('9000', '9003') THEN 1
		WHEN SUBSTR(A.ACCOUNT_NUMBER, 1, 4) = '9129' AND (CCF.VALUE = 0 OR CCF.VALUE = 1 OR CCF.CODE IS NULL) THEN 0.1
		WHEN A.ACCOUNT_NUMBER IN(90035300000471, 90036300000470) THEN 0.5
		ELSE CCF.VALUE
	END AS CCF_TO_CALC,
	ROUND((ACS.BASE_AMOUNT + NVL(RC.REZ_AMOUNT, 0)) * CASE
														WHEN CCF.CODE IS NULL AND SUBSTR(A.ACCOUNT_NUMBER, 1, 4) IN ('9000', '9003') THEN 1
														WHEN SUBSTR(A.ACCOUNT_NUMBER, 1, 4) = '9129' AND (CCF.VALUE = 0 OR CCF.VALUE = 1 OR CCF.CODE IS NULL) THEN 0.1
														WHEN A.ACCOUNT_NUMBER IN(90035300000471, 90036300000470) THEN 0.5
														ELSE CCF.VALUE
													  END, 2) AS SUM_TO_CALC
FROM SR_BANK.ACCOUNT_SNAPSHOT ACS
JOIN SR_BANK.ACCOUNT A 
	ON A.ID = ACS.ACCOUNT_ID
JOIN SR_BANK.CONTRACT_ACCOUNT CA 
	ON CA.ACCOUNT_ID = A.ID
JOIN SR_BANK.CREDIT_DOCUMENT CD 
	ON CD.ID = CA.CONTRACT_ID
LEFT JOIN SR_BANK.CCF_NBU CCF 
	ON (CCF.ID = CD.CCF_NBU_ID OR CCF.ID = CD.CCF_LIM_NBU_ID)
LEFT JOIN REZ_CTE RC 
	ON RC.CONTRACT_ID = CA.CONTRACT_ID
WHERE ACS.SNAPSHOT_DATE = TO_DATE(:date_param, 'DD.MM.YYYY')
	AND ACS.BASE_AMOUNT <> 0
	AND (
		SUBSTR(A.ACCOUNT_NUMBER, 1, 4) IN ('9000', '9001', '9002', '9003', '9100', '9200')
		OR (SUBSTR(A.ACCOUNT_NUMBER, 1, 4) = '9129' AND (CCF.CODE = '103_1' OR CCF.CODE = '29'))
		OR (SUBSTR(A.ACCOUNT_NUMBER, 1, 4) = '9200')
		)
ORDER BY 1
