SELECT
	C.ID AS REF_ID
	, CT.NAME AS TYPE
	, SD.ISIN
	, C.BEGIN_BASE_AMOUNT AS SUM
	, SD.ITEMS_NUMBER_IN_PCKGE AS COUNT_SD
FROM SR_BANK.SECURITY_DOCUMENT SD
INNER JOIN SR_BANK.CONTRACT C
	ON SD.ID = C.ID
INNER JOIN SR_BANK.COMPOUND_DOCUMENT CD
	ON SD.ID = CD.ID
INNER JOIN SR_BANK.CONTRACT_TYPE CT
	ON CT.ID = C.TYPE_ID
WHERE
	C.CLOSE_DATE IS NULL
	AND C.TYPE_ID IN (10074, 10075)
ORDER BY
    C.BEGIN_DATE DESC