SELECT
	SUBSTR(:data_acc, 1, 4) AS R020,
	d.ACCOUNT_DT,
	c.CODE AS CUR,
	d.ACCOUNT_CT,
	d.DESCRIPTION,
	d.BASE_AMOUNT AS SUM_UAH
FROM SR_BANK.DOCUMENT d
INNER JOIN SR_BANK.CURRENCY c
	ON d.CURRENCY_ID = c.ID
INNER JOIN SR_BANK.ACCOUNT a
	ON a.ACCOUNT_NUMBER = :data_acc
	AND a.ID IN (d.ACCOUNT_DEBIT_ID, d.ACCOUNT_CREDIT_ID)
WHERE
	d.POST_DATE = TO_DATE(:date_param, 'dd.mm.yyyy')
	AND c.CODE = :data_cur
ORDER BY d.ACCOUNT_DT, d.ACCOUNT_CT
