SELECT
	cd.DOC_NO,
	cd.DESCRIPTION,
	CASE
		WHEN cd.DESCRIPTION NOT LIKE '%980%' THEN '05'
		WHEN cd.DESCRIPTION LIKE '%980%' AND cd.DESCRIPTION LIKE '%Покупка%' THEN '01'
		WHEN cd.DESCRIPTION LIKE '%980%' AND cd.DESCRIPTION LIKE '%Продажа%' THEN '02'
		ELSE NULL
	END AS S135
FROM SR_BANK.COMPOUND_DOCUMENT cd
WHERE 
	cd.DOC_NO IN (:data_number)
	AND cd.DOC_DATE >= TRUNC(sysdate, 'yyyy')
	AND cd.DESCRIPTION IS NOT NULL
ORDER BY cd.DOC_NO