SELECT
	ca.CONTRACT_ID,
	a.ACCOUNT_NUMBER,
	c.CODE AS CUR,
	sd.INTEREST,
	acs.BASE_AMOUNT AS SUM_UAH,
	sd.LAST_CIRCULATION_DATE AS DATE_END
FROM SR_BANK.CONTRACT_ACCOUNT ca
INNER JOIN SR_BANK.CURRENCY c
    ON c.ID = ca.CURRENCY_ID
INNER JOIN SR_BANK.ACCOUNT_SNAPSHOT acs
	ON acs.ACCOUNT_ID = ca.ACCOUNT_ID
	AND acs.SNAPSHOT_DATE = to_date(:date_param, 'dd.mm.yyyy')
INNER JOIN SR_BANK.ACCOUNT a
	ON a.ID = ca.ACCOUNT_ID
INNER JOIN SR_BANK.SECURITY_DOCUMENT sd
	ON sd.ID = ca.CONTRACT_ID
WHERE ca.CONTRACT_ID IN (SELECT ca_anhor.CONTRACT_ID
						 FROM SR_BANK.CONTRACT_ACCOUNT ca_anhor
						 INNER JOIN SR_BANK.ACCOUNT a_anhor
						 	ON ca_anhor.ACCOUNT_ID = a_anhor.ID
						 WHERE a_anhor.ACCOUNT_NUMBER LIKE '1400%'
						 	AND a_anhor.IS_OPEN = 'T')
ORDER BY 1, 2