SELECT 
    TRUNC(asp.SNAPSHOT_DATE, 'DD') AS "Дата",
    cu.CODE AS "Код контрагента",
    a.NAME AS "Наименование контагента",
    a.ACCOUNT_NUMBER AS "Номер счета",
    c.CODE AS R030,
    CASE WHEN SUM(asp.AMOUNT) > 0 THEN 1 ELSE 2 END AS T020,
    SUBSTR(a.ACCOUNT_NUMBER, 1, 4) AS R020,
    SUM(asp.AMOUNT) AS "Остаток ном",
    SUM(asp.BASE_AMOUNT) AS "Остаток экв",
    ks245.CODE AS S245
FROM SR_BANK.ACCOUNT_SNAPSHOT asp
INNER JOIN SR_BANK.ACCOUNT a 
    ON a.ID = asp.ACCOUNT_ID
    AND (a.ACCOUNT_NUMBER LIKE '150%' 
         OR a.ACCOUNT_NUMBER LIKE '151%'
         OR a.ACCOUNT_NUMBER LIKE '152%'
         OR a.ACCOUNT_NUMBER LIKE '153%'
         OR a.ACCOUNT_NUMBER LIKE '154%'
         OR a.ACCOUNT_NUMBER LIKE '155%'
         OR a.ACCOUNT_NUMBER LIKE '183%')
LEFT JOIN SR_BANK.CURRENCY c 
    ON a.CURRENCY_ID = c.ID
LEFT JOIN SR_BANK.CUSTOMER cu
    ON a.CUSTOMER_ID = cu.ID
LEFT JOIN SR_BANK.ACCOUNT_ATTR_STAT s245
	ON a.ID = s245.ID
LEFT JOIN SR_BANK.KL_S245 ks245
	ON s245.KL_S245_ID = ks245.ID
WHERE asp.SNAPSHOT_DATE = :date_param
    AND asp.BASE_AMOUNT <> 0
    -- AND cu.CODE <> 12133 --НБУ
GROUP BY TRUNC(asp.SNAPSHOT_DATE, 'DD'),
    cu.CODE,
    a.NAME,
    a.ACCOUNT_NUMBER,
    c.CODE,
    SUBSTR(a.ACCOUNT_NUMBER, 1, 4),
	ks245.CODE