SELECT
	SUM(d.BASE_AMOUNT) AS Turnover,
	TO_CHAR(MAX(d.INPUT_DATE), 'HH24:MI:SS') AS Time
FROM SR_BANK.DOCUMENT d
WHERE
	d.ACCOUNT_CT LIKE '2652%'
	AND d.POST_DATE BETWEEN TO_DATE(:date_param, 'dd.mm.yyyy') AND TRUNC(sysdate, 'DAY')