SELECT
	SUBSTR(A.ACCOUNT_NUMBER, 1, 4) AS R020
	, TRUNC(ACS.SNAPSHOT_DATE, 'DD') AS RDATE
	, SUM(ACS.BASE_AMOUNT * NVL(CCF.VALUE, :ccf_param)) AS SUM
	-- , SUM(ACS.BASE_AMOUNT * NVL(CCF.VALUE, 1)) AS SUM
FROM SR_BANK.ACCOUNT_SNAPSHOT ACS
INNER JOIN SR_BANK.ACCOUNT A
	ON A.ID = ACS.ACCOUNT_ID
INNER JOIN SR_BANK.CONTRACT_ACCOUNT CA
	ON CA.ACCOUNT_ID = A.ID
LEFT JOIN SR_BANK.CREDIT_DOCUMENT CD
	ON CD.ID = CA.CONTRACT_ID 
LEFT JOIN SR_BANK.CCF_NBU CCF
	ON (CCF.ID = CD.CCF_NBU_ID OR CCF.ID = CD.CCF_LIM_NBU_ID)
WHERE 1=1
	AND ACS.SNAPSHOT_DATE = TO_DATE(:date_param, 'DD.MM.YYYY')
	AND ACS.BASE_AMOUNT <> 0
	AND (
		 SUBSTR(A.ACCOUNT_NUMBER, 1, 4) IN ('9000', '9003') 
		 OR (SUBSTR(A.ACCOUNT_NUMBER, 1, 4) = '9129' AND (CCF.CODE = '103_1' OR CCF.CODE = '29'))
	)
GROUP BY
	SUBSTR(A.ACCOUNT_NUMBER, 1, 4)
	, TRUNC(ACS.SNAPSHOT_DATE, 'DD')
	
UNION

SELECT
	SUBSTR(a.ACCOUNT_NUMBER, 1, 4) AS R020,
	acs.SNAPSHOT_DATE as RDATE, 
	SUM(ABS(acs.BASE_AMOUNT)) * -1 AS SUM
FROM SR_BANK.ACCOUNT a
LEFT JOIN SR_BANK.ACCOUNT_SNAPSHOT acs
	ON a.ID = acs.ACCOUNT_ID
LEFT JOIN SR_BANK.ACCOUNT_ATTR_STAT aas
	ON a.ID = aas.ID
JOIN SR_BANK.KL_R013 r013
	ON aas.KL_R013_ID = r013.ID
WHERE 
	(a.ACCOUNT_NUMBER LIKE '2932%' OR a.ACCOUNT_NUMBER LIKE '9500%')
	AND a.IS_OPEN = 'T'
	AND acs.SNAPSHOT_DATE = TO_DATE(:date_param, 'dd.mm.yyyy')
	AND r013.CODE IN ('1', '5')
GROUP BY 
	SUBSTR(a.ACCOUNT_NUMBER, 1, 4),
	acs.SNAPSHOT_DATE
ORDER BY 1;