SELECT 
	d.POST_DATE,
	d.ACCOUNT_DT,
	d.ACCOUNT_CT,
	c.SHORT_NAME,
	d.AMOUNT,
	d.BASE_AMOUNT,
	d.DESCRIPTION
FROM SR_BANK.DOCUMENT d
JOIN SR_BANK.CURRENCY c
	ON c.ID = d.CURRENCY_ID
WHERE 1=1
	AND d.POST_DATE = to_date(:date_param, 'dd.mm.yyyy')
	AND :date_acc IN (d.ACCOUNT_DT, d.ACCOUNT_CT)