SELECT
	R020
	, NVL(OLD_DATE, 0) AS OLD_DATE
	, NVL(ACTUAL_DATE, 0) AS ACTUAL_DATE
	, NVL(ACTUAL_DATE, 0) - NVL(OLD_DATE, 0) AS DIFF
	, (NVL(ACTUAL_DATE,0) - NVL(OLD_DATE, 0)) * CASE 
													WHEN R020 LIKE '%-NBU' THEN 0
													WHEN R020 = '9200' THEN 0.5
													WHEN R020 = '9350' THEN 0.5
													ELSE 1
	  											END AS EFFECT_ON_EXPOSURE
FROM  (SELECT 
	TRUNC(ACS.SNAPSHOT_DATE, 'DD') AS RDATE
	, CASE 
		WHEN R011.CODE = '5' THEN SUBSTR(A.ACCOUNT_NUMBER, 1, 4) || '-NBU'
		WHEN (SUBSTR(A.ACCOUNT_NUMBER, 1, 4) = '9200' AND A.NAME LIKE '%Національний%') THEN SUBSTR(A.ACCOUNT_NUMBER, 1, 4) || '-NBU'
		ELSE SUBSTR(A.ACCOUNT_NUMBER, 1, 4)
	END AS R020
	, SUM(ACS.BASE_AMOUNT) AS SUM_UAH
	FROM SR_BANK.ACCOUNT A
	LEFT JOIN SR_BANK.CURRENCY CUR
		ON CUR.ID = A.CURRENCY_ID
	LEFT JOIN SR_BANK.CUSTOMER C
		ON C.ID = A.CUSTOMER_ID
	LEFT JOIN SR_BANK.ACCOUNT_ATTR_STAT ATS
		ON ATS.ID = A.ID
	LEFT JOIN SR_BANK.KL_R011 R011
		ON R011.ID = ATS.KL_R011_ID
	LEFT JOIN SR_BANK.KL_R013 R013
		ON R013.ID = ATS.KL_R013_ID
	LEFT JOIN SR_BANK.KL_S245 S245
		ON S245.ID = ATS.KL_S245_ID
	LEFT JOIN SR_BANK.KL_S580 S580
		ON S580.ID = ATS.KL_S580_ID
	LEFT JOIN SR_BANK.KL_R019 R019
		ON R019.ID = ATS.KL_R019_ID
	LEFT JOIN SR_BANK.ACCOUNT_SNAPSHOT ACS
		ON ACS.ACCOUNT_ID = A.ID
	WHERE 1=1
		AND A.IS_OPEN = 'T'
		AND ACS.BASE_AMOUNT <> 0
		AND SUBSTR(A.ACCOUNT_NUMBER, 1, 4) IN (1811, 1819, 9200, 9350)
		AND TRUNC(ACS.SNAPSHOT_DATE, 'DD') BETWEEN TO_DATE(:date_param_old, 'DD.MM.YYYY')
										       AND TO_DATE(:date_param, 'DD.MM.YYYY')
	GROUP BY
		TRUNC(ACS.SNAPSHOT_DATE, 'DD')
		, CASE 
			WHEN R011.CODE = '5' THEN SUBSTR(A.ACCOUNT_NUMBER, 1, 4) || '-NBU'
			WHEN (SUBSTR(A.ACCOUNT_NUMBER, 1, 4) = '9200' AND A.NAME LIKE '%Національний%') THEN SUBSTR(A.ACCOUNT_NUMBER, 1, 4) || '-NBU'
			ELSE SUBSTR(A.ACCOUNT_NUMBER, 1, 4)
		END)
	
PIVOT (SUM(SUM_UAH)
	FOR RDATE IN (TO_DATE(:date_param_old, 'DD.MM.YYYY') AS OLD_DATE,
				  TO_DATE(:date_param, 'DD.MM.YYYY') AS ACTUAL_DATE)
       )
ORDER BY 1