SELECT
	CASE
		WHEN a.ACCOUNT_NUMBER LIKE '4300%1' THEN 'A6R027'
		WHEN a.ACCOUNT_NUMBER LIKE '4309%1' THEN 'A6R028'
		WHEN a.ACCOUNT_NUMBER LIKE '4300%2' THEN 'A6R025'
		ELSE 'A6R026'
	END AS EKP,
	ABS(acs.BASE_AMOUNT) AS SUM,
	a.ACCOUNT_NUMBER AS LS
FROM SR_BANK.ACCOUNT_SNAPSHOT acs
JOIN SR_BANK.ACCOUNT a
	ON a.ID = acs.ACCOUNT_ID
WHERE 
	acs.SNAPSHOT_DATE = TO_DATE(:date_param, 'dd.mm.yyyy')
	AND SUBSTR(a.ACCOUNT_NUMBER, 1, 4) IN (4300, 4309)
ORDER BY 1