SELECT
	CD.DOC_NO 
	, SD.ISIN
	, SD.ONE_ITEM_NOMINAL_VAL AS COST_ONE_SECUR
	, SD.ITEMS_NUMBER_IN_PCKGE AS COUNT_SECUR
FROM SR_BANK.SECURITY_DOCUMENT SD
INNER JOIN SR_BANK.CONTRACT C
	ON SD.ID = C.ID
INNER JOIN SR_BANK.COMPOUND_DOCUMENT CD
	ON SD.ID = CD.ID
WHERE
	C.CLOSE_DATE IS NULL
ORDER BY
    C.BEGIN_DATE DESC